### ISSUE TITLE
Bootcamp Feedback TODO

### ISSUE THREAD

**Issue by danilolab** [carolprotasio/pipa-burgers#10]
Deixo como sugestão os seguintes tópicos:
- [x] Aprofundar os estudos no Angular, quanto à modularização e componentização
- [x] Escrever os testes unitários
- [x] Criar projetos pessoais, para crianças e/ou familiares e publicar no git para demonstrar seus conhecimentos
- [x] Refazer alguns exercícios da GYM focados em design e backend
- [x] Recomendação de sites: https://www.hackerrank.com/, https://leetcode.com/ e https://www.codewars.com/

**Comment by carolprotasio** [comment]
done
